# Generated by Django 3.2.10 on 2022-05-24 13:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.CharField(max_length=64)),
                ('data', models.JSONField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.batch')),
            ],
        ),
        migrations.RunSQL("CREATE INDEX idx_objects_key ON app_objects((data->'key'));"),
        migrations.RunSQL("CREATE INDEX idx_objects_value ON app_objects((data->'value'));"),
    ]
